// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI_iM7mzrkzca3i2gFtqp9reVV7fcUTkY',
    appId: '1:955682491827:web:c137a6b7e31f8591850fc6',
    messagingSenderId: '955682491827',
    projectId: 'medicalapp124',
    authDomain: 'medicalapp124.firebaseapp.com',
    storageBucket: 'medicalapp124.appspot.com',
    measurementId: 'G-JNV44D4F10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATn_dFJVnW_MUouTjdwkiiaXURjLITEHc',
    appId: '1:955682491827:android:2f2debf158da5270850fc6',
    messagingSenderId: '955682491827',
    projectId: 'medicalapp124',
    storageBucket: 'medicalapp124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2kjbt7eGABjcv1SomP-sTp9O6lre7gXw',
    appId: '1:955682491827:ios:b4324a804baa5d4e850fc6',
    messagingSenderId: '955682491827',
    projectId: 'medicalapp124',
    storageBucket: 'medicalapp124.appspot.com',
    iosBundleId: 'com.example.project7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kjbt7eGABjcv1SomP-sTp9O6lre7gXw',
    appId: '1:955682491827:ios:b4324a804baa5d4e850fc6',
    messagingSenderId: '955682491827',
    projectId: 'medicalapp124',
    storageBucket: 'medicalapp124.appspot.com',
    iosBundleId: 'com.example.project7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI_iM7mzrkzca3i2gFtqp9reVV7fcUTkY',
    appId: '1:955682491827:web:6045d7788660eaf3850fc6',
    messagingSenderId: '955682491827',
    projectId: 'medicalapp124',
    authDomain: 'medicalapp124.firebaseapp.com',
    storageBucket: 'medicalapp124.appspot.com',
    measurementId: 'G-C3T3RMBNXL',
  );
}
